settings:
  title: 'Status Page'
  url: 'https://status.benji.link' # used for Slack messages
  logo: loading.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: benji-link # unique identifier
    name: benji.link
    description: 'My Website.' # default=empty
    url: 'https://benji.link/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: bench-benji-link
    name: bench.benji.link
    description: 'Cloud Servies Benchmarked.'
    url: 'https://bench.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: dash-benji-link
    name: dash.benji.link
    description: 'Showing off my past projects.'
    url: 'https://dash.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
 
  - id: home-benji-link
    name: home.benji.link
    description: 'Turn on/off the lights in my room.'
    url: 'https://home.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: bot-benji-link
    name: bot.benji.link
    description: 'Create a Bot easily.'
    url: 'https://bot.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: effi-wtf
    name: effi.benji.link
    description: 'Just a stupid Effi website. 2.0'
    url: 'https://effi.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: durak-benji-link
    name: durak.benji.link
    description: 'Stats for a card game called Durak.'
    url: 'https://durak.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
   
  - id: short-benji-link
    name: short.benji.link
    description: 'Simple link shortner.'
    url: 'https://short.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: frantic-benji-link
    name: frantic.benji.link
    description: 'Simple frantic counter.'
    url: 'https://frantic.benji.link/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
